#!/bin/zsh

# if we're on mac..
if [[ `uname` == "Darwin" ]]; then
    which -s brew
    if [[ $? != 0 ]] ; then
        # Install Homebrew
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        brew update
        brew upgrade

        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        for file in $(ls -A | grep -vE '\.git$|\.gitignore|.*.md|\bootstrap') ; do
            ln -sv "$PWD/$file" "$HOME"
        done

        source ~/.zprofile
        source ~/.zshrc

        brew install ruby
        brew install zsh-syntax-highlighting
        brew tap homebrew/cask-fonts
        brew cask install font-hack-nerd-font
        brew isntall python
        brew install byobu 
        brew install cloudflare/cloudflare/cloudflared
        gem install colorls

    fi
fi
source ~/.local.bootstrap

